In [27]:
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import pandas as pd

In [28]:
df = pd.read_csv('train.txt', sep=';', header=None, names=['text', 'emotion'])

In [29]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [30]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [31]:
unique_emotions= df['emotion'].unique()
emotion_number ={}
i=0
for emo in unique_emotions:
    emotion_number[emo] = i
    i+=1 
df['emotion'] = df['emotion'].map(emotion_number)

In [32]:

df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [33]:
df['text'] = df['text'].apply(lambda x: x.lower())

In [34]:
import string
def remove_punctuation(text):
    return text.translate(str.maketrans('', '',string.punctuation))

In [35]:
df['text'] = df['text'].apply(remove_punctuation)

In [36]:
def remove_numbers(text):
    return ''.join([i for i in text if not i.isdigit()])

In [37]:
def remove_numbers(text):
    return ''.join([i for i in text if not i.isdigit()])

df['text'] = df['text'].apply(remove_numbers)

In [38]:
import re
def remove_links(text):
    return re.sub(r'http\S+', '', text)
df['text'] = df['text'].apply(remove_links)

In [39]:
def remove_emojis(text):
    return text.encode('ascii', 'ignore').decode('ascii')

df['text'] = df['text'].apply(remove_emojis)

In [49]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [51]:

stop_words = set(stopwords.words('english'))
def remove_stopwords(text):
    
    words = word_tokenize(text)
    return ' '.join([w for w in words if w.lower() not in stop_words])
df['text'] = df['text'].apply(remove_stopwords)